name: CI-coverage

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          configuration: tests/phpunit.xml
          args: --coverage-text
        env:
          XDEBUG_MODE: coverage

      - name: Generate test coverage badge
          uses: ./
          with:
            coverage_badge_path: 'badge.svg'
            push_badge: true
            repo_token: ${{ secrets.GITHUB_TOKEN }}