name: CI-PHP-STAN

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: PHPStan Static Analysis source code
        uses: php-actions/phpstan@v3
        with:
          path: src/
          level: 5

      - name: PHPStan Static Analysis tests code
        uses: php-actions/phpstan@v3
        with:
          path: tests/
          level: 5
