name: CI-PHP-CS

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: PHP Code Style
        uses: chindit/actions-phpcs@master
        with:
          dir: src/
